name: Test

on:
  pull_request:
    branches:
      - "master"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set Up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install pytest and flake8
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run flake8
        run: flake8 app/
      - name: Run tests
        run: pytest tests/

